apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: addons
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/elsabahnur/argocd.git
        revision: HEAD
        directories:
          - path: /*           
  template:
    metadata:
      name: '{{path.basename}}'  
    spec:
      project: addons
      source:
        repoURL: https://github.com/elsabahnur/argocd.git
        targetRevision: HEAD
        path: '{{path.basename}}' #'{{path}}/{{path[2]}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path}}' 
