apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd
resources:
- https://raw.githubusercontent.com/argoproj/argo-cd/v2.7.2/manifests/install.yaml
- addons-appset.yaml
- addons-proj.yaml


patches:
  - path: argocd-cm.yaml
